<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="UtilityOperatorsIntegrationTest" tests="1" skipped="0" failures="1" errors="0" timestamp="2019-10-20T14:37:38" hostname="Minhaz-MacBook-Pro.local" time="0.26">
  <properties/>
  <testcase name="givenObservable_whenSubscribeOn_thenEmitsEventsOnComputeScheduler" classname="UtilityOperatorsIntegrationTest" time="0.26">
    <failure message="java.lang.NullPointerException" type="java.lang.NullPointerException">java.lang.NullPointerException
	at org.awaitility.core.CallableCondition$ConditionEvaluationWrapper.eval(CallableCondition.java:99)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:203)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:190)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
</failure>
  </testcase>
  <system-out><![CDATA[Emitting 100 on thread RxComputationThreadPool-1
Emitting again 100 on thread RxComputationThreadPool-1
Emitting 200 on thread RxComputationThreadPool-1
Emitting again 200 on thread RxComputationThreadPool-1
Received 1000 on thread RxCachedThreadScheduler-1
Emitting 300 on thread RxComputationThreadPool-1
Received 2000 on thread RxCachedThreadScheduler-1
Emitting again 300 on thread RxComputationThreadPool-1
Emitting 400 on thread RxComputationThreadPool-1
Received 3000 on thread RxCachedThreadScheduler-1
Emitting again 400 on thread RxComputationThreadPool-1
Emitting 500 on thread RxComputationThreadPool-1
Received 4000 on thread RxCachedThreadScheduler-1
Emitting again 500 on thread RxComputationThreadPool-1
Received 5000 on thread RxCachedThreadScheduler-1
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
